#!/bin/bash
# Copy interesting files to this repository
# Only for my internal use.

# Config target path
cfg="cfg"

if [ ! -d "$cfg" ]; then 
	mkdir -v "$cfg"
fi

## Obtain kernel [source] arch and release
kern_src=$(readlink /usr/src/linux)
kern_cfg="$kern_src/.config"
tmp=($(head -n3 "$kern_cfg" | tail -1 | cut -d " " -f 2,3))
kern_arch=${tmp[0]/*\//}
kern_rel=${tmp[1]}
unset tmp

## Local bashrc
bash_cfg="$HOME/.bashrc"

## Pekwm config
pekwm_path="$HOME/.pekwm"

## Copy files
 
# Copy files to modified targets
cp -v "$kern_cfg" "$cfg/linux-${kern_rel}-${kern_arch}.config"
cp -v "$bash_cfg" "$cfg/bashrc-local"

# Copy files
for f in "/etc/mkinitrd.conf" \
	  "/etc/profile" \
	  "/etc/rc.d/rc.local" \
	  "/etc/rc.d/rc.modules" \
	  "/usr/bin/xwmconfig" \
	  "/etc/X11/xinit/xinitrc.pekwm"; do
	cp -v "$f" "$cfg/"
done
