#!/bin/bash
# - Copy interesting files
# - Generate some output files
# Only for my internal use.

# Config target
cfg="cfg"

# Output target
dump="output"

if [ ! -d "$cfg" ]; then 
	mkdir -v "$cfg"
fi

if [ ! -d "$dump" ]; then 
	mkdir -v "$dump"
fi

## Obtain kernel [source] arch and release
kern_src=$(readlink /usr/src/linux)
kern_cfg="$kern_src/.config"
tmp=($(head -n3 "$kern_cfg" | tail -1 | cut -d " " -f 2,3))
kern_arch=${tmp[0]/*\//}
kern_rel=${tmp[1]}
unset tmp

## Local bashrc
bash_cfg="$HOME/.bashrc"

## Copy files
cp -v "$kern_cfg" "$cfg/linux-${kern_rel}-${kern_arch}.config"
cp -v "$bash_cfg" "$cfg/bashrc-local"

for f in "/etc/mkinitrd.conf" \
	  "/etc/profile" \
	  "/etc/rc.d/rc.local" \
	  "/etc/rc.d/rc.modules" \
	  "/usr/bin/xwmconfig" \
	  "/etc/X11/xinit/xinitrc.pekwm"; do
	cp -v "$f" "$cfg/"
done

## Dump system info
lspci -vv > "$dump/lspci"
lsusb -v > "$dump/lsusb"

lshw -short > "$dump/lshw-short"
lshw -businfo > "$dump/lshw-businfo"
lshw -html > "$dump/lshw.html"
